"""Add index to recipe external_recipe_id

Revision ID: 264edf2066a0
Revises: 49a8d842be50
Create Date: 2026-01-04 12:27:25.988032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264edf2066a0'
down_revision = '49a8d842be50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_external_recipe_id'), ['external_recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_external_recipe_id'))

    # ### end Alembic commands ###
