"""Add session_id to transcription_jobs

Revision ID: 895767e8ad21
Revises: 20241224addstatus
Create Date: 2025-12-26 13:47:18.415474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895767e8ad21'
down_revision = '20241224addstatus'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))
    
    # Update existing rows with a default session_id
    op.execute("UPDATE transcription_jobs SET session_id = 'legacy-' || CAST(id AS TEXT) WHERE session_id IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.alter_column('session_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
